server:
  port: 8761

eureka:
  instance:
    hostname: server1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://server2:8762/eureka,http://server3:8763/eureka